version: '3.8'
services:
  database:
    image: postgres:13
    container_name: db_red_social
    restart: always
    environment:
      POSTGRES_PASSWORD: facebook
      POSTGRES_USER: post
      POSTGRES_DB: postgres_db
    ports:
      - 5440:5432
    volumes:
      - ./data/postgres:/var/lib/postgres
